export const CLIENTS_LIST_REQUEST = "CLIENTS_LIST_REQUEST";
export const CLIENTS_LIST_SUCCESS = "CLIENTS_LIST_SUCCESS";
export const CLIENTS_LIST_FAIL = "CLIENTS_LIST_FAIL";

export const CLIENTS_CREATE_REQUEST = "CLIENTS_CREATE_REQUEST";
export const CLIENTS_CREATE_SUCCESS = "CLIENTS_CREATE_SUCCESS";
export const CLIENTS_CREATE_FAIL = "CLIENTS_CREATE_FAIL";

export const CLIENTS_UPDATE_REQUEST = "CLIENTS_UPDATE_REQUEST";
export const CLIENTS_UPDATE_SUCCESS = "CLIENTS_UPDATE_SUCCESS";
export const CLIENTS_UPDATE_FAIL = "CLIENTS_UPDATE_FAIL";

export const CLIENTS_DELETE_REQUEST = "CLIENTS_DELETE_REQUEST";
export const CLIENTS_DELETE_SUCCESS = "CLIENTS_DELETE_SUCCESS";
export const CLIENTS_DELETE_FAIL = "CLIENTS_DELETE_FAIL";

export const CLIENTS_DASHBOARD_REQUEST = "CLIENTS_DASHBOARD_REQUEST";
export const CLIENTS_DASHBOARD_SUCCESS = "CLIENTS_DASHBOARD_SUCCESS";
export const CLIENTS_DASHBOARD_FAIL = "CLIENTS_DASHBOARD_FAIL";

export const CLIENTS_NOTIFY_REQUEST = "CLIENTS_NOTIFY_REQUEST";
export const CLIENTS_NOTIFY_SUCCESS = "CLIENTS_NOTIFY_SUCCESS";
export const CLIENTS_NOTIFY_FAIL = "CLIENTS_NOTIFY_FAIL";
